SELECT * FROM OSB.FARMACIAS;

--PARA CONSULTAR LOS MSJ QUE LLEGAN A OSB
SELECT * FROM SIMUSER.STAGED_MESSAGE WHERE TRUNC(CREATE_TIME)>='09/03/17'
AND BUSINESS_ID LIKE '%FAO-CODPROD-1003-20170309-13:36%';

SELECT * FROM SIMUSER.STAGED_MESSAGE WHERE 
 BUSINESS_ID LIKE 'ae6248e5-25e2-1ed7-8199-16ed871bc507%' ORDER BY ID DESC;

--este sql me muestra los productos por cada farmacias y productos
SELECT SHORT_DESC,RK_LONG_DESC, ID_STR_RT FROM SIMUSER.AS_ITM_RTL_STR WHERE ID_STR_RT='1060';



--ESTE QUERY NOS MOSTRA EL PRECIO SIN IVA AL CUAL LE DEBEMOS CALCULAR EL 12% Y EL PROVEEDOR DEL PRODUCTO A CONSULTAR
SELECT RP_SLS_CRT AS PRECIO_SIN_IVA, ID_SPR AS PROVEEDOR, DC_PRC_SLS_EF_CRT AS FECHA FROM SIMUSER.AS_ITM_RTL_STR WHERE ID_ITM=104541;

--PARA CONSULTAR EL PROVEEDOR
SELECT * FROM SIMUSER.AS_ITM_RTL_STR WHERE ID_ITM=104541;


AND ID_STR_RT='1047';

SELECT * FROM SIMUSER.PA_STR_RTL;

-- LA TABLA DE TODOS LOS PRODUCTOS DE LA CADENA
SELECT * FROM SIMUSER.AS_ITM;

--ESTE QUERY ME MUESTRA TODOS LOS UPC
SELECT AS_ITM.ID_PRT_ITM AS ID_ITM, 
AS_ITM.ID_ITM AS UPC
FROM SIMUSER.AS_ITM 
WHERE AS_ITM.ID_PRT_ITM IS NOT NULL;

--ESTE QUERY NOS MUESTRA TODOS LOS MSJ QUE LLEGAN A OSB
SELECT * FROM OSB.ITEMS_DETAILS
--WHERE BS_ID like '%FAO-CODPROD-1118-20170105-10:04%'
--WHERE PHARMACY_ID=01049
--WHERE ID_TBL=2
ORDER BY TS_REG desc; 


SELECT * FROM OSB.VW_CHANGE_LOG_INTEG_FAR;

  
SELECT bs_id, pharmacy_id, id_tbl, act_typ,  MAX(id_log) id_log
      FROM   OSB.items_details
      WHERE  NVL(IND_ORSIM,'N') = 'N'
        AND trunc(ts_reg) >= trunc(sysdate -3)
        --('ae6248e5-25e2-1ee6-9bbe-e54467795f07-1') -- solventado
        --in ('ae6248e5-25e2-1ed6-9bbe-e617a8f55407-1') Malo solo deba hacer UPDATE
        --AND ROWNUM <= 100
      GROUP BY BS_ID, PHARMACY_ID, ID_TBL, ACT_TYP
      ORDER BY 3 asc;

--PARA VER QUE PRODUCTO HAY EN ESPECIFICO EN CADA FARMACIAS
SELECT * FROM AS_ITM@XE@FAO_01008;

SELECT ID_STR_RT, IP FROM OSB.FARMACIAS ORDER BY ID_STR_RT;

SELECT * FROM OSB.FARMACIAS;

--PARA CONSULTAR LOS MSJ QUE LLEGAN A OSB ORSIM
SELECT * FROM SIMUSER.STAGED_MESSAGE WHERE PROCESSED='N' AND MESSAGE_FAMILY='ItemLoc' AND RETRY_COUNT<3 and BUSINESS_ID LIKE '%ae6248e5-25e2-1ed7-819a-9228d8eedd05%';

SELECT * FROM SIMUSER.STAGED_MESSAGE WHERE TRUNC(CREATE_TIME)>='19/01/17';
--and BUSINESS_ID LIKE '%FAO-CODPROD-1047-20170119-10:08%';

--este sql me muestra los productos por cada farmacias y productos
SELECT ID_ITM,SHORT_DESC,RK_LONG_DESC, ID_STR_RT FROM SIMUSER.AS_ITM_RTL_STR WHERE ID_STR_RT='1002';

--este sql me muestra los productos por cada farmacias
SELECT * FROM SIMUSER.AS_ITM_RTL_STR WHERE ID_ITM=104541 AND ID_STR_RT='1075';

SELECT * FROM SIMUSER.AS_ITM_RTL_STR;


-- LA TABLA DE TODOS LOS PRODUCTOS DE LA CADENA
SELECT ID_ITM AS SKU, DEPT_ID AS DEPARTAMENTO, CLASS_ID AS CLASE, SUBCLASS_ID AS SUB_CLASE, DE_ITM AS DESCRIPCION FROM SIMUSER.AS_ITM;

--ESTE QUERY ME MUESTRA TODOS LOS UPC ORSIM
SELECT AS_ITM.ID_PRT_ITM AS SKU, 
AS_ITM.ID_ITM AS UPC,
AS_ITM.RK_LONG_DESC AS NAME
FROM SIMUSER.AS_ITM 
WHERE AS_ITM.ID_PRT_ITM IS NOT NULL;
AND ID_PRT_ITM IN(
'314758',
'314759',
'314760',
'314761',
'305123',
'314762',
'314763',
'314764',
'314765',
'314688',
'314689',
'314690'
)ORDER BY ID_ITM ASC;

LOS UPC QUE MANDA SAP
SELECT DISTINCT ID_ITM,UPC,TRUNC(TS_REG) FROM OSB.ITEMS_UPC
WHERE ID_ITM IN(
'314758',
'314759',
'314760',
'314761',
'305123',
'314762',
'314763',
'314764',
'314765',
'314688',
'314689',
'314690')
ORDER BY 3 DESC;

--ESTO VA A ORBO
SELECT * FROM OSB.ITEMS_DETAILS
--WHERE BS_ID like '%ae6248e5-25e2-1ee7-819a-93746fc4dc07%'
--WHERE PHARMACY_ID=01049
--WHERE ID_TBL=2
ORDER BY TS_REG desc;


SELECT DISTINCT ID_ITM,UPC FROM OSB.ITEMS_UPC;

--UPC QUE MANDO SAP LO CONSULTO CON EL ID_LOG
SELECT * FROM OSB.ITEMS_UPC;

SELECT * FROM OSB.SUMMER;



 
SELECT * FROM SIMUSER.VW_ORBO_ITEM_TYPE_INTEG;                                         /* productos*/
 
SELECT * FROM SIMUSER.VW_ORBO_ITEMUPC_TYPE_INTEG;                                /* UPC*/
 
SELECT * FROM SIMUSER.VW_ORBO_PRICECHANGE_TYPE_INTEG;                     /* PRECIOS*/
 
SELECT COUNT(*) FROM OSB.VW_CHANGE_LOG_INTEG_FAR;

SELECT * FROM OSB.VW_CHANGE_LOG_INTEG_FAR;

SELECT * FROM SIMUSER.STAGED_MESSAGE WHERE MESSAGE_TYPE='PosTransaction' and PROCESSED='N';




SELECT * FROM SIMUSER.RK_HIERARCHY WHERE DEPT_ID=12;
AND ID=20 AND CLASS_ID=20 AND SUBCLASS_ID=30; 
1202030
--TABLE DE DONDE LA INTERFAZ ORSIM TOMA LOS DATOS (Location):
select ID_STR_RT AS FARMACIA,ID_ITM as SKU, SHORT_DESC as DESCRIPCION from SIMUSER.AS_ITM_RTL_STR where ID_ITM='314521';
select * from SIMUSER.AS_ITM_RTL_STR where ID_ITM='104541';

SELECT ID_SPR AS ID_PROVEEDOR, NM_SPR AS NAME  FROM SIMUSER.PA_SPR;